In [2]:
import pandas as pd
import matplotlib as plt

In [9]:
from pathlib import Path

file_path = Path("data/raw.csv")

print("File exists:", file_path.exists())
print("Absolute path:", file_path.resolve())

File exists: True
Absolute path: C:\Users\pranav\Desktop\pocket_money_transaction\data\raw.csv

In [3]:

df = pd.read_csv("data/raw.csv")

print("CSV loaded successfully!")
print(df.shape)
display(df.head())

CSV loaded successfully!
(559, 8)

,Transaction Statement for 9644090543,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,Duration,"14 Oct, 2025 - 14 Oct, 2026",NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Date,Time,Transaction Details,Transaction ID,UTR,Transaction Type,Credit/debit instrument,Amount
3,13-Oct-26,6:07 PM,Paid to NARENDRA KUMAR DESHMUKH,T2610131807285889986487,5.69562E+11,DEBIT,Paid by XXXXXX0575,50
4,13-Oct-26,12:53 PM,Received from Prem Dilliwar,T2610131253386653253851,6.65274E+11,CREDIT,Credited to XXXXXX0575,50

In [6]:
df.tail()

,Transaction Statement for 9644090543,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
554,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
555,Disclaimer : Do not fall prey to fictitious of...,money circulation schemes and cheap funds,NaN,NaN,NaN,NaN,NaN,NaN
556,etc. through SMS,emails and calls. The contents of this email ...,NaN,NaN,NaN,NaN,NaN,NaN
557,the recipient specified in this document. If y...,please inform PhonePe at,NaN,NaN,NaN,NaN,NaN,NaN
558,https://support.phonepe.com/statement so that ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(12, 5))
sns.heatmap(df.isna(), cbar=False, yticklabels=False)
plt.title("Missing Values in Transaction Dataset")
plt.xlabel("Columns")
plt.show()

In [11]:
df.describe()

,Transaction Statement for 9644090543,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
count,556,552,548,548,548,548,548,548
unique,243,398,241,548,545,3,3,128
top,15-Jul-26,1:01 PM,Received from Prem Dilliwar,T2510141301180993352961,6.11418E+11,DEBIT,Paid by XXXXXX0575,20
freq,11,4,44,1,2,393,393,61

In [14]:
df.columns = df.columns.str.strip()

print(df.columns.tolist())

['Transaction Statement for 9644090543', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7']

In [13]:
print("Dataset shape:", df.shape)
print("UTR column exists:", "UTR" in df.columns)

display(df.head(10))

print("\nRemaining Paid to prefixes:")
print(
    df["Transaction Details"]
    .str.contains(r"^\s*Paid to\b", case=False, na=False)
    .sum()
)

print("\nRemaining Received from prefixes:")
print(
    df["Transaction Details"]
    .str.contains(r"^\s*Received from\b", case=False, na=False)
    .sum()
)

Dataset shape: (559, 8)
UTR column exists: False

,Transaction Statement for 9644090543,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,Duration,"14 Oct, 2025 - 14 Oct, 2026",NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Date,Time,Transaction Details,Transaction ID,UTR,Transaction Type,Credit/debit instrument,Amount
3,13-Oct-26,6:07 PM,Paid to NARENDRA KUMAR DESHMUKH,T2610131807285889986487,5.69562E+11,DEBIT,Paid by XXXXXX0575,50
4,13-Oct-26,12:53 PM,Received from Prem Dilliwar,T2610131253386653253851,6.65274E+11,CREDIT,Credited to XXXXXX0575,50
5,13-Oct-26,11:36 AM,Paid to SHIVAM PALIWAL,T2610131136103063239030,99818369878,DEBIT,Paid by XXXXXX0575,200
6,13-Oct-26,11:26 AM,Paid to V Annapurna Annapurna,T2610131126304976733713,9.76217E+11,DEBIT,Paid by XXXXXX0575,18
7,12-Oct-26,5:06 PM,Paid to POOJA BAKERY AND DAILY NEEDS,T2610121706239909334382,7.75186E+11,DEBIT,Paid by XXXXXX0575,20
8,12-Oct-26,1:03 PM,Paid to MUSKAN SAHU,T2610121303283853068878,9.95935E+11,DEBIT,Paid by XXXXXX0575,20
9,12-Oct-26,12:32 PM,Received from Ankush Mishra,T2610121232165564448170,6.28526E+11,CREDIT,Credited to XXXXXX0575,50

Remaining Paid to prefixes:

KeyError: 'Transaction Details'

In [8]:
# Remove UTR column
df = df.drop(columns=["UTR"])

# Remove transaction prefixes
df["Transaction Details"] = (
    df["Transaction Details"]
    .astype("string")
    .str.replace(
        r"^\s*(?:Paid to|Received from)\s+",
        "",
        regex=True,
        case=False
    )
    .str.strip()
)

print(df.head())
print(df.columns.tolist())

KeyError: "['UTR'] not found in axis"

In [9]:
df = pd.read_csv(
    "data/raw.csv",
    skiprows=4,
    header=None,
    names=[
        "Date",
        "Time",
        "Transaction Details",
        "Transaction ID",
        "UTR",
        "Transaction Type",
        "Credit/debit instrument",
        "Amount"
    ]
)

print(df.head())

        Date      Time                    Transaction Details  \
0  13-Oct-26   6:07 PM        Paid to NARENDRA KUMAR DESHMUKH
1  13-Oct-26  12:53 PM           Received from Prem  Dilliwar
2  13-Oct-26  11:36 AM                 Paid to SHIVAM PALIWAL
3  13-Oct-26  11:26 AM          Paid to V Annapurna Annapurna
4  12-Oct-26   5:06 PM  Paid to POOJA BAKERY AND DAILY NEEDS

            Transaction ID           UTR Transaction Type  \
0  T2610131807285889986487  5.695620e+11            DEBIT
1  T2610131253386653253851  6.652740e+11           CREDIT
2  T2610131136103063239030  9.981837e+10            DEBIT
3  T2610131126304976733713  9.762170e+11            DEBIT
4  T2610121706239909334382  7.751860e+11            DEBIT

  Credit/debit instrument  Amount
0      Paid by XXXXXX0575    50.0
1  Credited to XXXXXX0575    50.0
2      Paid by XXXXXX0575   200.0
3      Paid by XXXXXX0575    18.0
4      Paid by XXXXXX0575    20.0

In [10]:
df = pd.read_csv("data/raw.csv", skiprows=3)
df.columns = df.columns.str.strip()

df = df.drop(columns=["UTR"])

df["Transaction Details"] = (
    df["Transaction Details"]
    .astype("string")
    .str.replace(
        r"^\s*(?:Paid to|Received from)\s+",
        "",
        regex=True,
        case=False
    )
    .str.strip()
)

In [11]:
df.head()

,Date,Time,Transaction Details,Transaction ID,Transaction Type,Credit/debit instrument,Amount
0,13-Oct-26,6:07 PM,NARENDRA KUMAR DESHMUKH,T2610131807285889986487,DEBIT,Paid by XXXXXX0575,50.0
1,13-Oct-26,12:53 PM,Prem Dilliwar,T2610131253386653253851,CREDIT,Credited to XXXXXX0575,50.0
2,13-Oct-26,11:36 AM,SHIVAM PALIWAL,T2610131136103063239030,DEBIT,Paid by XXXXXX0575,200.0
3,13-Oct-26,11:26 AM,V Annapurna Annapurna,T2610131126304976733713,DEBIT,Paid by XXXXXX0575,18.0
4,12-Oct-26,5:06 PM,POOJA BAKERY AND DAILY NEEDS,T2610121706239909334382,DEBIT,Paid by XXXXXX0575,20.0

In [12]:
df.to_csv("data/cleaned_transactions.csv", index=False)